name: Acceptance

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.2.0
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - name: eslint
        run: yarn lint --quiet
